encoding: utf-8
name: Treefrog Framework
markdown: kramdown
kramdown:  
  parse_block_html: true
github: [metadata]
gems: [markdown]
theme: jekyll-theme-slate
baseurl: ''
url: https://thomasgueldner.github.io/thomas.gueldner

# Server
source: docs
port: 4000
