encoding: utf-8
name: Treefrog Framework
markdown: kramdown
kramdown:  
  parse_block_html: true
github: [metadata]
gems: [markdown]
theme: jekyll-theme-slate
baseurl: /thomas.gueldner/docs

# Server
source:       docs
port:         4000
