name: 		Treefrog Framework
markdown: 	kramdown
highlighter: rouge

github: 	[metadata]
gems: 		[markdown]
theme: 		jekyll-theme-slate
url: 		https://thomasgueldner.github.io

sass:
    sass_dir: _sass/

# Server
source: 	docs
port: 		4000
encoding: 	utf-8
